format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
${custom.aws_sso_hours}\
$line_break\
$status\
$shell\
$character
"""

command_timeout = 1000

[hostname]
ssh_only = false

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = ""
modified = "ğŸ“ ${count}"
ahead = "â¬†${count}"
behind = "â¬‡${count}"

[aws] 
# format = '$symbol$duration'
expiration_symbol = "â›ˆï¸"

[custom.aws_sso_hours]
command = 'aws_sso_hours'
format = '[$output]($style)'
shell = 'bash'
when = true
